compressionLevel: mixed

enableGlobalCache: false

enableTelemetry: 0

supportedArchitectures:
  cpu:
    - x64
    - arm64
  libc:
    - glibc
    - musl
  os:
    - linux

yarnPath: .yarn/releases/yarn-4.0.2.cjs
