name: CI

on: [push, pull_request]

jobs:
  build-test-and-publish:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node:
          - 14
          - 16

        include:
          - node: 14
            publish: true
            continue-on-error: false

    continue-on-error: ${{ matrix.continue-on-error == true }}

    container:
      image: node:${{ matrix.node }}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Validate the dependencies
        run: yarn install --immutable --immutable-cache

      - name: Compile
        run: yarn run compile

      - name: Test
        run: yarn run test

      - name: Publish to npmjs
        if: "matrix.publish == true && startsWith(github.ref, 'refs/tags/')"
        run: |
          npm version --no-git-tag-version ${GITHUB_REF#refs/tags/}
          yarn npm publish --tolerate-republish --access public
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_REGISTRY_AUTH_TOKEN }}
